/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{html,jsx,js}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['DM Sans', 'sans-serif'],
      },
      colors: {
        onSurfaceVariant: {
          DEFAULT: '#52443B', // light
          dark: '#D7C2B9',    // dark
        },
        light: {
          primary: '#FB8C00',
          surfaceTint: '#FB8C00',
          onPrimary: '#FFFFFF',
          primaryContainer: '#FFDDBC',
          onPrimaryContainer: '#2B1900',
          secondary: '#765849',
          onSecondary: '#FFFFFF',
          secondaryContainer: '#FFDBC8',
          onSecondaryContainer: '#2B160B',
          tertiary: '#656032',
          onTertiary: '#FFFFFF',
          tertiaryContainer: '#ECE5AB',
          onTertiaryContainer: '#1F1C00',
          error: '#BA1A1A',
          onError: '#FFFFFF',
          errorContainer: '#FFDAD6',
          onErrorContainer: '#410002',
          background: '#FFF8F5',
          onBackground: '#201A17',
          surface: '#FFF8F5',
          onSurface: '#201A17',
          surfaceVariant: '#F3DFD2',
          onSurfaceVariant: '#52443B',
          outline: '#85736A',
          outlineVariant: '#D7C2B9',
          shadow: '#000000',
          scrim: '#000000',
          inverseSurface: '#362F2B',
          inverseOnSurface: '#FBEEE8',
          inversePrimary: '#FFB86B',
          primaryFixed: '#FFDDBC',
          onPrimaryFixed: '#2B1900',
          primaryFixedDim: '#FFB86B',
          onPrimaryFixedVariant: '#8B4D00',
          secondaryFixed: '#FFDBC8',
          onSecondaryFixed: '#2B160B',
          secondaryFixedDim: '#E7BEA9',
          onSecondaryFixedVariant: '#5C4134',
          tertiaryFixed: '#ECE5AB',
          onTertiaryFixed: '#1F1C00',
          tertiaryFixedDim: '#CFC992',
          onTertiaryFixedVariant: '#4B471D',
          surfaceDim: '#EBD9D1',
          surfaceBright: '#FFF8F5',
          surfaceContainerLowest: '#FFFFFF',
          surfaceContainerLow: '#FFF2EB',
          surfaceContainer: '#F8ECE7',
          surfaceContainerHigh: '#F3E6E0',
          surfaceContainerHighest: '#EDE0DA',
        },
        dark: {
          primary: '#FFB86B',
          surfaceTint: '#FFB86B',
          onPrimary: '#492900',
          primaryContainer: '#8B4D00',
          onPrimaryContainer: '#FFDDBC',
          secondary: '#E7BEA9',
          onSecondary: '#43291F',
          secondaryContainer: '#5C4134',
          onSecondaryContainer: '#FFDBC8',
          tertiary: '#CFC992',
          onTertiary: '#353107',
          tertiaryContainer: '#4B471D',
          onTertiaryContainer: '#ECE5AB',
          error: '#FFB4AB',
          onError: '#690005',
          errorContainer: '#93000A',
          onErrorContainer: '#FFDAD6',
          background: '#171210',
          onBackground: '#EDE0DA',
          surface: '#171210',
          onSurface: '#EDE0DA',
          surfaceVariant: '#52443B',
          onSurfaceVariant: '#D7C2B9',
          outline: '#A08D84',
          outlineVariant: '#52443B',
          shadow: '#000000',
          scrim: '#000000',
          inverseSurface: '#EDE0DA',
          inverseOnSurface: '#362F2B',
          inversePrimary: '#FB8C00',
          primaryFixed: '#FFDDBC',
          onPrimaryFixed: '#2B1900',
          primaryFixedDim: '#FFB86B',
          onPrimaryFixedVariant: '#8B4D00',
          secondaryFixed: '#FFDBC8',
          onSecondaryFixed: '#2B160B',
          secondaryFixedDim: '#E7BEA9',
          onSecondaryFixedVariant: '#5C4134',
          tertiaryFixed: '#ECE5AB',
          onTertiaryFixed: '#1F1C00',
          tertiaryFixedDim: '#CFC992',
          onTertiaryFixedVariant: '#4B471D',
          surfaceDim: '#171210',
          surfaceBright: '#3E3632',
          surfaceContainerLowest: '#120D0B',
          surfaceContainerLow: '#201A17',
          surfaceContainer: '#251F1B',
          surfaceContainerHigh: '#2F2925',
          surfaceContainerHighest: '#3A332F',
        },
      },
      space: {
        0: '0px',
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        7: '28px',
        8: '32px',
        9: '36px',
        10: '40px',
        11: '44px',
        12: '48px',
        13: '52px',
        14: '56px',
        15: '60px',
        16: '64px',
        17: '68px',
        18: '72px',
        19: '76px',
        20: '80px',
        21: '84px',
        22: '88px',
        23: '92px',
        24: '96px',
        25: '100px',
        26: '104px',
        27: '108px',
        28: '112px',
        29: '116px',
        30: '120px',
      },
      boxShadow: {
        elevation1:
          '0px 1px 2px 0px rgba(0, 0, 0, 0.30), 0px 1px 3px 1px rgba(0, 0, 0, 0.15)',
        elevation2:
          '0px 1px 2px 0px rgba(0, 0, 0, 0.30), 0px 2px 6px 2px rgba(0, 0, 0, 0.15)',
        elevation3:
          '0px 4px 8px 3px rgba(0, 0, 0, 0.15), 0px 1px 3px 0px rgba(0, 0, 0, 0.30)',
        elevation4:
          '0px 6px 10px 4px rgba(0, 0, 0, 0.15), 0px 2px 3px 0px rgba(0, 0, 0, 0.30)',
        elevation5:
          '0px 8px 12px 6px rgba(0, 0, 0, 0.15), 0px 4px 4px 0px rgba(0, 0, 0, 0.30)',
      },
      borderRadius: {
        none: '0',
        extraSmall: '4px',
        small: '8px',
        medium: '12px',
        large: '16px',
        extraLarge: '28px',
        full: '1000px',
      },
      fontSize: {
        displayLarge: [
          '57px',
          {
            fontWeight: '400',
            lineHeight: '64px',
            letterSpacing: '-0.25px',
          },
        ],
        displayMedium: [
          '45px',
          {
            fontWeight: '400',
            lineHeight: '52px',
            letterSpacing: '0',
          },
        ],
        displaySmall: [
          '36px',
          {
            fontWeight: '400',
            lineHeight: '44px',
            letterSpacing: '0',
          },
        ],
        headlineLarge: [
          '32px',
          {
            fontWeight: '400',
            lineHeight: '40px',
            letterSpacing: '0',
          },
        ],
        headlineMedium: [
          '28px',
          {
            fontWeight: '400',
            lineHeight: '36px',
            letterSpacing: '0',
          },
        ],
        headlineSmall: [
          '24px',
          {
            fontWeight: '400',
            lineHeight: '32px',
            letterSpacing: '0',
          },
        ],
        titleLarge: [
          '22px',
          {
            fontWeight: '400',
            lineHeight: '28px',
            letterSpacing: '0',
          },
        ],
        titleMedium: [
          '16px',
          {
            fontWeight: '500',
            lineHeight: '24px',
            letterSpacing: '0.15px',
          },
        ],
        titleSmall: [
          '14px',
          {
            fontWeight: '500',
            lineHeight: '20px',
            letterSpacing: '0.1px',
          },
        ],
        bodyLarge: [
          '16px',
          {
            fontWeight: '400',
            lineHeight: '24px',
            letterSpacing: '0.5px',
          },
        ],
        bodyMedium: [
          '14px',
          {
            fontWeight: '400',
            lineHeight: '20px',
            letterSpacing: '0.25px',
          },
        ],
        bodySmall: [
          '12px',
          {
            fontWeight: '400',
            lineHeight: '16px',
            letterSpacing: '0.4px',
          },
        ],
        labelLarge: [
          '14px',
          {
            fontWeight: '500',
            lineHeight: '20px',
            letterSpacing: '0.1px',
          },
        ],
        labelMedium: [
          '12px',
          {
            fontWeight: '500',
            lineHeight: '16px',
            letterSpacing: '0.5px',
          },
        ],
        labelSmall: [
          '11px',
          {
            fontWeight: '500',
            lineHeight: '16px',
            letterSpacing: '0.5px',
          },
        ],
      },
      transitionDuration: {
        short1: '50ms',
        short2: '100ms',
        short3: '150ms',
        short4: '200ms',
        medium1: '250ms',
        medium2: '300ms',
        medium3: '350ms',
        medium4: '400ms',
        long1: '450ms',
        long2: '500ms',
        long3: '550ms',
        long4: '600ms',
        extraLong1: '700ms',
        extraLong2: '800ms',
        extraLong3: '900ms',
        extraLong4: '1000ms',
      },
      transitionDelay: {
        short1: '50ms',
        short2: '100ms',
        short3: '150ms',
        short4: '200ms',
        medium1: '250ms',
        medium2: '300ms',
        medium3: '350ms',
        medium4: '400ms',
        long1: '450ms',
        long2: '500ms',
        long3: '550ms',
        long4: '600ms',
        extraLong1: '700ms',
        extraLong2: '800ms',
        extraLong3: '900ms',
        extraLong4: '1000ms',
      },
      transitionTimingFunction: {
        standard: 'cubic-bezier(0.2, 0, 0, 1)',
        standardDecelerate: 'cubic-bezier(0, 0, 0, 1)',
        standardAccelerate: 'cubic-bezier(0.3, 0, 1, 1)',
        emphasized: 'cubic-bezier(0.2, 0, 0, 1.0)',
        emphasizedDecelerate: 'cubic-bezier(0.05, 0.7, 0.1, 1)',
        emphasizedAccelerate: 'cubic-bezier(0.3, 0, 0.8, 0.15)',
        legacy: 'cubic-bezier(0.4, 0, 0.2, 1.0)',
        legacyDecelerate: 'cubic-bezier(0, 0, 0.2, 1)',
        legacyAccelerate: 'cubic-bezier(0.4, 0, 1, 1)',
        linear: 'cubic-bezier(0, 0, 1, 1)',
      },
    },
  },
  plugins: [],
};