"""documents appartient à l'utilisateur

Revision ID: 9b49bab197b7
Revises: 1a768c03688b
Create Date: 2025-09-04 03:59:18.035848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b49bab197b7'
down_revision: Union[str, None] = '1a768c03688b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_document_link',
    sa.Column('conversation_uid', sa.Uuid(), nullable=False),
    sa.Column('document_uid', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_uid'], ['conversations.uid'], ),
    sa.ForeignKeyConstraint(['document_uid'], ['documents.uid'], ),
    sa.PrimaryKeyConstraint('conversation_uid', 'document_uid')
    )
    op.create_index('idx_conversation_document_link', 'conversation_document_link', ['conversation_uid', 'document_uid'], unique=False)
    op.add_column('documents', sa.Column('user_uid', sa.Uuid(), nullable=False))
    op.drop_index('idx_document_conversation', table_name='documents')
    op.drop_index('ix_documents_conversation_uid', table_name='documents')
    op.create_index('idx_document_user', 'documents', ['user_uid'], unique=False)
    op.create_index(op.f('ix_documents_user_uid'), 'documents', ['user_uid'], unique=False)
    op.drop_constraint('documents_conversation_uid_fkey', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['user_uid'], ['uid'])
    op.drop_column('documents', 'conversation_uid')
    op.drop_column('documents', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('conversation_uid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_conversation_uid_fkey', 'documents', 'conversations', ['conversation_uid'], ['uid'])
    op.drop_index(op.f('ix_documents_user_uid'), table_name='documents')
    op.drop_index('idx_document_user', table_name='documents')
    op.create_index('ix_documents_conversation_uid', 'documents', ['conversation_uid'], unique=False)
    op.create_index('idx_document_conversation', 'documents', ['conversation_uid'], unique=False)
    op.drop_column('documents', 'user_uid')
    op.drop_index('idx_conversation_document_link', table_name='conversation_document_link')
    op.drop_table('conversation_document_link')
    # ### end Alembic commands ###
